name: PUSH Github-Actions. github contexts .
on:
  push:
    branches:
      - task/github-action-context/github**

jobs:
  FIRST-JOB:
    name: ${{ github.job }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "01. ☆Action name is ${{ github.action }}. Head-label:false,log:true"
      - run: echo "02. ★Action Path is ${{ github.action_path }}. Head-label:false,log:false; This result is Valid. Cause, only supported in composite actions"
      - run: echo "03. Execute by ${{ github.actor }}. Head-label:true,log:true"
      - run: echo "04. Event object is ${{ github.event }}. Head-label:true,log:true"
      - run: echo "05. Event name is ${{ github.event_name }}. Head-label:true,log:true"
      - run: echo "06. ☆Event path is ${{ github.event_path }}. Head-label:false,log:true"
      - run: echo "07. ★Target branch  name is ${{ github.base_ref }}. Head-label:false,log:false; This result is Valid. Cause, pull_request or pull_request_target event only."
      - run: echo "08. Current branch name is ${{ github.ref }}. Head-label:true,log:true"
      - run: echo "09. ★head_ref is ${{ github.head_ref }}. Head-label:false,log:false; This result is Valid. Cause, pull_request or pull_request_target event only."
      - run: echo "10. ☆Current job-id is ${{ github.job }}. Head-label:false,log:true"
      - run: echo "11. OWNER/repository is ${{ github.repository }}. Head-label:true,log:true"
      - run: echo "12. Repository Owner is ${{ github.repository_owner }}. Head-label:true,log:true"
      - run: echo "13. Run id is ${{ github.run_id }}. Head-label:true,log:true"
      - run: echo "14. Run number is ${{ github.run_number }}. Head-label:true,log:true"
      - run: echo "15. Run attempt is ${{ github.run_attempt }}. Head-label:true,log:true"
      - run: echo "16. Server URL is ${{ github.server_url }}. Head-label:true,log:true"
      - run: echo "17. Commit id is ${{ github.sha }}. Head-label:true,log:true"
      - run: echo "18. Github Token is ${{ github.token }}."
      - run: echo "19. Work flow or full path of workflow file is ${{ github.workflow }}. Head-label:true,log:true"
      - run: echo "20. ☆Default working directory is ${{ github.workspace }}. Head-label:false,log:true"

