name: PULL REQUEST Github-Actions. github contexts.
on:
  pull_request:
    types:
      - opened
    branches:
      - task/github-action-context/github**

jobs:
  FIRST-JOB:
    name: ${{ github.job }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "01. Action name is ${{ github.action }}."
      - run: echo "02. Action Path is ${{ github.action_path }}."
      - run: echo "03. Execute by ${{ github.actor }}."
      - run: echo "04. Event object is ${{ github.event }}."
      - run: echo "05. Event name is ${{ github.event_name }}."
      - run: echo "06. Event path is ${{ github.event_path }}."
      - run: echo "07. Target branch  name is ${{ github.base_ref }}."
      - run: echo "08. Current branch name is ${{ github.ref }}."
      - run: echo "09. head_ref is ${{ github.head_ref }}."
      - run: echo "10. Current job-id is ${{ github.job }}."
      - run: echo "11. OWNER/repository is ${{ github.repository }}."
      - run: echo "12. Repository Owner is ${{ github.repository_owner }}."
      - run: echo "13. Run id is ${{ github.run_id }}."
      - run: echo "14. Run number is ${{ github.run_number }}."
      - run: echo "15. Run attempt is ${{ github.run_attempt }}."
      - run: echo "16. Server URL is ${{ github.server_url }}."
      - run: echo "17. Commit id is ${{ github.sha }}."
      - run: echo "18. Github Token is {{ github.token }}."
      - run: echo "19. Work flow or full path of workflow file is ${{ github.workflow }}."
      - run: echo "20. Default working directory is ${{ github.workspace }}."
